[project]
name = "volga_test"
version = "1.0.0"
dependencies = [
    "pydantic>=2.8.2",
    "pydantic-settings>=2.4.0",
    "sqlalchemy>=2.0.32",
    "psycopg>=3.2.0",
    "aiohttp>=3.10.0",
    "pandas>=2.2.2",
    "openpyxl",
]